-- Fitness Goals, generated by ChatGPT
INSERT INTO personal_bot.t_fitness_goal_statuses (name)
VALUES
    ('Planned'),
    ('In Progress'),
    ('Achieved'),
    ('Cancelled');

-- Fitness Targets, generated by ChatGPT
INSERT INTO personal_bot.t_fitness_targets (name)
VALUES
    ('Weight Loss'),
    ('Muscle Gain'),
    ('Improved Endurance'),
    ('Body Recomposition'),
    ('Increased Flexibility'),
    ('Injury Recovery');

-- Measures, generated by ChatGPT
INSERT INTO personal_bot.t_measures (name)
VALUES
    ('Weight (lbs)'),
    ('Body Fat Percentage'),
    ('Muscle Mass Percentage'),
    ('Resting Heart Rate (bpm)'),
    ('Blood Pressure (mmHg)'),
    ('Waist Circumference (in)'),
    ('Hip Circumference (in)'),
    ('Bicep Circumference (in)'),
    ('Thigh Circumference (in)');