/*
Copyright 2023 Juan Jose Vargas Fletes

This work is licensed under the Creative Commons Attribution-NonCommercial (CC BY-NC) license.
To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0/

Under the CC BY-NC license, you are free to:

- Share: copy and redistribute the material in any medium or format
- Adapt: remix, transform, and build upon the material

Under the following terms:

  - Attribution: You must give appropriate credit, provide a link to the license, and indicate if changes were made.
    You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

- Non-Commercial: You may not use the material for commercial purposes.

You are free to use this work for personal or non-commercial purposes.
If you would like to use this work for commercial purposes, please contact Juan Jose Vargas Fletes at juanvfletes@gmail.com.
*/

-- Common Health Conditions, generated by ChatGPT
INSERT INTO personal_bot.t_health_conditions (name, description)
VALUES
    ('Diabetes', 'A metabolic disease characterized by high blood sugar levels.'),
    ('Obesity', 'A condition characterized by excess body fat that increases the risk of health problems.'),
    ('Heart Disease', 'A group of conditions that affect the structure and function of the heart.'),
    ('Hypertension', 'High blood pressure, a condition in which the force of blood against the artery walls is too high.'),
    ('Celiac Disease', 'An autoimmune disorder in which the ingestion of gluten leads to damage in the small intestine.'),
    ('Crohn''s Disease', 'A type of inflammatory bowel disease that can affect any part of the gastrointestinal tract.'),
    ('Ulcerative Colitis', 'A chronic inflammatory bowel disease that causes inflammation and ulcers in the digestive tract.'),
    ('Gallstones', 'Hard deposits that form in the gallbladder and can cause severe abdominal pain.'),
    ('Kidney Disease', 'A condition in which the kidneys are damaged and cannot filter blood properly.'),
    ('Liver Disease', 'A condition in which the liver is damaged and cannot function properly.'),
    ('Pancreatitis', 'An inflammation of the pancreas that can cause severe abdominal pain.'),
    ('Polycystic Ovary Syndrome (PCOS)', 'A hormonal disorder that can cause irregular periods and difficulty getting pregnant.'),
    ('Thyroid Disorders', 'Conditions that affect the thyroid gland and can cause a variety of symptoms, including weight gain or loss.'),
    ('Inflammatory Arthritis', 'A type of arthritis that causes inflammation in the joints.'),
    ('Osteoporosis', 'A condition in which bones become weak and brittle.');

-- Common Activity Levels, generated by ChatGPT
INSERT INTO personal_bot.t_activity_levels (name, description)
VALUES
    ('Sedentary', 'Little or no exercise and a desk job.'),
    ('Lightly Active', 'Light exercise or sports 1-3 days a week.'),
    ('Moderately Active', 'Moderate exercise or sports 3-5 days a week.'),
    ('Very Active', 'Hard exercise or sports 6-7 days a week.'),
    ('Super Active', 'Very hard exercise or sports, physical job or training twice a day.');