#Copyright 2023 Juan Jose Vargas Fletes
#
#This work is licensed under the Creative Commons Attribution-NonCommercial (CC BY-NC) license.
#To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0/
#
#Under the CC BY-NC license, you are free to:
#
#- Share: copy and redistribute the material in any medium or format
#- Adapt: remix, transform, and build upon the material
#
#Under the following terms:
#
#  - Attribution: You must give appropriate credit, provide a link to the license, and indicate if changes were made.
#    You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
#
#- Non-Commercial: You may not use the material for commercial purposes.
#
#You are free to use this work for personal or non-commercial purposes.
#If you would like to use this work for commercial purposes, please contact Juan Jose Vargas Fletes at juanvfletes@gmail.com.

services:
  personal_bot:
    image: personal_bot:1.0.0
    depends_on:
      - personal_bot_db
    ports:
      - "443:443"
    links:
      - "personal_bot_db:database"
      
  personal_bot_db:
    image: personal_bot_db:1.0.0
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    links:
      - "personal_bot_db:database"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
