version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_PASSWORD
    ports:
      - "5438:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
